const EXPRESS_PORT = 3000;
const EXPRESS_TIMEOUT = 2048;

const DB_RETRIES = 3;

const MAX_TRADE_RESULTS = 1000;
const TICKER_REGEX = /^[a-zA-Z]+_[a-zA-Z]+$/;

module.exports = { DB_RETRIES, MAX_TRADE_RESULTS, TICKER_REGEX, EXPRESS_PORT, EXPRESS_TIMEOUT }